#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x1A541148054E9E38 (infra-root@openstack.org)
#
Name     : oslo.versionedobjects
Version  : 1.34.1
Release  : 40
URL      : http://tarballs.openstack.org/oslo.versionedobjects/oslo.versionedobjects-1.34.1.tar.gz
Source0  : http://tarballs.openstack.org/oslo.versionedobjects/oslo.versionedobjects-1.34.1.tar.gz
Source99 : http://tarballs.openstack.org/oslo.versionedobjects/oslo.versionedobjects-1.34.1.tar.gz.asc
Summary  : Oslo Versioned Objects library
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.versionedobjects-license = %{version}-%{release}
Requires: oslo.versionedobjects-python = %{version}-%{release}
Requires: oslo.versionedobjects-python3 = %{version}-%{release}
Requires: Sphinx
Requires: WebOb
Requires: fixtures
Requires: iso8601
Requires: netaddr
Requires: openstackdocstheme
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.context
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.messaging
Requires: oslo.serialization
Requires: oslo.utils
Requires: python-mock
Requires: reno
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pbr

%description
Team and repository tags
        ========================

%package license
Summary: license components for the oslo.versionedobjects package.
Group: Default

%description license
license components for the oslo.versionedobjects package.


%package python
Summary: python components for the oslo.versionedobjects package.
Group: Default
Requires: oslo.versionedobjects-python3 = %{version}-%{release}

%description python
python components for the oslo.versionedobjects package.


%package python3
Summary: python3 components for the oslo.versionedobjects package.
Group: Default
Requires: python3-core

%description python3
python3 components for the oslo.versionedobjects package.


%prep
%setup -q -n oslo.versionedobjects-1.34.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1541271174
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/oslo.versionedobjects
cp LICENSE %{buildroot}/usr/share/package-licenses/oslo.versionedobjects/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/oslo.versionedobjects/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
