#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : oslo.versionedobjects
Version  : 1.17.0
Release  : 26
URL      : http://tarballs.openstack.org/oslo.versionedobjects/oslo.versionedobjects-1.17.0.tar.gz
Source0  : http://tarballs.openstack.org/oslo.versionedobjects/oslo.versionedobjects-1.17.0.tar.gz
Summary  : Oslo Versioned Objects library
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.versionedobjects-python
BuildRequires : Pygments
BuildRequires : Routes-python
BuildRequires : Sphinx-python
BuildRequires : WebOb-python
BuildRequires : anyjson-python
BuildRequires : coverage-python
BuildRequires : docutils-python
BuildRequires : extras
BuildRequires : extras-python
BuildRequires : hacking
BuildRequires : iso8601-python
BuildRequires : msgpack-python-python
BuildRequires : netaddr
BuildRequires : netifaces-python
BuildRequires : oslo.i18n-python
BuildRequires : oslo.log-python
BuildRequires : oslo.messaging-python
BuildRequires : oslo.serialization-python
BuildRequires : oslo.utils-python
BuildRequires : oslosphinx-python
BuildRequires : oslotest-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pyinotify-python
BuildRequires : pyrsistent-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-mimeparse-python
BuildRequires : python3-dev
BuildRequires : repoze.lru-python
BuildRequires : setuptools
BuildRequires : testtools
BuildRequires : testtools-python
BuildRequires : tox
BuildRequires : traceback2-python
BuildRequires : unittest2-python
BuildRequires : virtualenv

%description
===================================
oslo.versionedobjects
===================================

%package python
Summary: python components for the oslo.versionedobjects package.
Group: Default
Requires: WebOb-python
Requires: iso8601-python
Requires: netaddr
Requires: oslo.i18n-python
Requires: oslo.log-python
Requires: oslo.messaging-python
Requires: oslo.serialization-python
Requires: oslo.utils-python

%description python
python components for the oslo.versionedobjects package.


%prep
%setup -q -n oslo.versionedobjects-1.17.0

%build
export LANG=C
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
