#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xB9069B1335700CDC (infra-root@openstack.org)
#
Name     : oslo.versionedobjects
Version  : 1.23.0
Release  : 36
URL      : http://tarballs.openstack.org/oslo.versionedobjects/oslo.versionedobjects-1.23.0.tar.gz
Source0  : http://tarballs.openstack.org/oslo.versionedobjects/oslo.versionedobjects-1.23.0.tar.gz
Source99 : http://tarballs.openstack.org/oslo.versionedobjects/oslo.versionedobjects-1.23.0.tar.gz.asc
Summary  : Oslo Versioned Objects library
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.versionedobjects-python
Requires: WebOb
Requires: fixtures
Requires: iso8601
Requires: netaddr
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.context
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.messaging
Requires: oslo.serialization
Requires: oslo.utils
Requires: python-mock
Requires: six
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
========================
Team and repository tags
========================
.. image:: http://governance.openstack.org/badges/oslo.versionedobjects.svg
:target: http://governance.openstack.org/reference/tags/index.html

%package python
Summary: python components for the oslo.versionedobjects package.
Group: Default

%description python
python components for the oslo.versionedobjects package.


%prep
%setup -q -n oslo.versionedobjects-1.23.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1490884654
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1490884654
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
